### ISSUE TITLE
Seems like a update blocks ForceAttack

### ISSUE THREAD

**Issue by Vandiliz3r** [kadeeq/ProjectX#119]
Traceback (most recent call last):
  File "D:\AMDProfiler\CSGO\ProjectX_V2.py", line 8, in <module>
    from Classes.PlayerVars import *
  File "D:\AMDProfiler\CSGO\Classes\PlayerVars.py", line 1, in <module>
    from Utils.Offsets import *
  File "D:\AMDProfiler\CSGO\Utils\Offsets.py", line 83, in <module>
    dwForceAttack = get_sig(pm1, "client.dll", bytes(PatternDict["dwForceAttack"], encoding="raw_unicode_escape"), 0, 2)
  File "D:\AMDProfiler\CSGO\Utils\Offsets.py", line 48, in get_sig
    match = re.search(pattern, bytes).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by SourLen** [comment]
This is actually a quite common error message, most of the time it does not actully have something to do with an update but can be fixed by just restarting the game, the program or if nothing works just restarting your pc. 
If the issue should persist please message me again and I will take a look when I come home from work tonight.
