### ISSUE TITLE
idk i just opened the app today morning and it saying this

### ISSUE THREAD

**Issue by ghostof1337projects** [kadeeq/ProjectX#127]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\TOOLS\Python-CSGO-Cheat-main\ProjectX_V2.py", line 8, in <module>
    from Classes.PlayerVars import *
  File "C:\Users\Admin\Desktop\TOOLS\Python-CSGO-Cheat-main\Classes\PlayerVars.py", line 1, in <module>
    from Utils.Offsets import *
  File "C:\Users\Admin\Desktop\TOOLS\Python-CSGO-Cheat-main\Utils\Offsets.py", line 75, in <module>
    dwLocalPlayer = get_sig(pm1, "client.dll", bytes(PatternDict["dwLocalPlayer"], encoding="raw_unicode_escape"), 4, 3)
  File "C:\Users\Admin\Desktop\TOOLS\Python-CSGO-Cheat-main\Utils\Offsets.py", line 48, in get_sig
    match = re.search(pattern, bytes).start()
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by SourLen** [comment]
Just restarting your pc should fix the issue, otherwise feel free to comment again
